// Generated by https://quicktype.io

class CurrentModel {
  int time;
  String summary;
  String icon;
  int precipIntensity;
  int precipProbability;
  double temperature;
  double apparentTemperature;
  double dewPoint;
  double humidity;
  int pressure;
  double windSpeed;
  double windGust;
  int windBearing;
  double cloudCover;
  int uvIndex;
  double visibility;
  int ozone;

  CurrentModel({
    this.time,
    this.summary,
    this.icon,
    this.precipIntensity,
    this.precipProbability,
    this.temperature,
    this.apparentTemperature,
    this.dewPoint,
    this.humidity,
    this.pressure,
    this.windSpeed,
    this.windGust,
    this.windBearing,
    this.cloudCover,
    this.uvIndex,
    this.visibility,
    this.ozone,
  });

  CurrentModel fromJson(Map<String, dynamic> city) {
    return CurrentModel(
      time: city['time'],
      summary: city['summary'],
      icon: city['icon'],
      precipIntensity: city['precipIntensity'],
      precipProbability: city['precipProbability'],
      temperature: city['temperature'].toDouble(),
      apparentTemperature: city['apparentTemperature'].toDouble(),
      dewPoint: city['dewPoint'].toDouble(),
      humidity: city['humidity'].toDouble(),
      pressure: city['pressure'],
      windSpeed: city['windSpeed'].toDouble(),
      windGust: city['windGust'].toDouble(),
      windBearing: city['windBearing'],
      cloudCover: city['cloudCover'].toDouble(),
      uvIndex: city['uvIndex'],
      visibility: city['visibility'].toDouble(),
      ozone: city['ozone'],
    );
  }
}
