// Generated by https://quicktype.io

class DarkSkyCurrent {
  int time;
  String summary;
  String icon;
  int precipIntensity;
  int precipProbability;
  double temperature;
  double apparentTemperature;
  double dewPoint;
  double humidity;
  double pressure;
  double windSpeed;
  double windGust;
  int windBearing;
  int cloudCover;
  int uvIndex;
  int visibility;
  double ozone;

  DarkSkyCurrent({
    this.time,
    this.summary,
    this.icon,
    this.precipIntensity,
    this.precipProbability,
    this.temperature,
    this.apparentTemperature,
    this.dewPoint,
    this.humidity,
    this.pressure,
    this.windSpeed,
    this.windGust,
    this.windBearing,
    this.cloudCover,
    this.uvIndex,
    this.visibility,
    this.ozone,
  });

  DarkSkyCurrent fromJson(Map<String, dynamic> json) {
    return DarkSkyCurrent(
      temperature: json['temperature'],
      humidity: json['humidity'],
      icon: json['icon'],
      windSpeed: json['windSpeed'],
      precipProbability: json['precipProbability'],
    );
  }
}
