// Generated by https://quicktype.io

class Hourly {
  int time;
  String summary;
  String icon;
  double precipIntensity;
  double precipProbability;
  String precipType;
  double temperature;
  double apparentTemperature;
  double dewPoint;
  double humidity;
  double pressure;
  double windSpeed;
  double windGust;
  int windBearing;
  double cloudCover;
  int uvIndex;
  double visibility;
  double ozone;

  Hourly(
      {this.time,
      this.summary,
      this.icon,
      this.precipIntensity,
      this.precipProbability,
      this.precipType,
      this.temperature,
      this.apparentTemperature,
      this.dewPoint,
      this.humidity,
      this.pressure,
      this.windSpeed,
      this.windGust,
      this.windBearing,
      this.cloudCover,
      this.uvIndex,
      this.visibility,
      this.ozone});

  String tempRound() => this.temperature.round().toString();
  Hourly fromJson(Map<String, dynamic> json) {
    return Hourly(
      time: json['time'].toInt(),
      summary: json['summary'],
      icon: json['icon'],
      precipIntensity: json['precipIntensity'].toDouble(),
      precipProbability: json['precipProbability'].toDouble(),
      precipType: json['precipType'],
      temperature: json['temperature'].toDouble(),
      apparentTemperature: json['apparentTemperature'].toDouble(),
      dewPoint: json['dewPoint'].toDouble(),
      humidity: json['humidity'].toDouble(),
      pressure: json['pressure'].toDouble(),
      windSpeed: json['windSpeed'].toDouble(),
      windGust: json['windGust'].toDouble(),
      windBearing: json['windBearing'].toInt(),
      cloudCover: json['cloudCover'].toDouble(),
      uvIndex: json['uvIndex'].toInt(),
      visibility: json['visibility'].toDouble(),
      ozone: json['ozone'].toDouble(),
    );
  }
}
